name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package + test deps
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"

      - name: Run flake8 (style)
        run: |
          pip install flake8
          flake8 src tests

      - name: Run pytest with coverage
	run: |
   	  pytest -v --cov=sde_estim --cov-report=xml
      - name: Upload coverage to Codecov
	  uses: codecov/codecov-action@v4
  		with:
    		fail_ci_if_error: true
    		files: coverage.xml          # le fichier généré
	
	

